language: python
addons:
    firefox: "52.0esr"
python:
    - 2.7
before_install:
    - "export DISPLAY=:99"
    - "sh -e /etc/init.d/xvfb start"
install:
    - "mkdir var"
    - "wget https://github.com/mozilla/geckodriver/releases/download/v0.15.0/geckodriver-v0.15.0-linux64.tar.gz"
    - "mkdir geckodriver"
    - "tar -xzf geckodriver-v0.15.0-linux64.tar.gz -C geckodriver"
    - "export PATH=$PATH:$PWD/geckodriver"
    - "pip install -r requirements/travis.txt"
env:
    - TOX_ENV=django111
matrix:
  include:
    - python: 2.7
      env: TOX_ENV=quality
script:
    - tox -e $TOX_ENV
notifications:
  email: false
branches:
    only:
        - master
deploy:
  provider: pypi
  user: edx
  password:
    secure: celTh9NJzWzxRMCo+uXDkmFIvQ1uvqBuDHwW/hVcN0gO9Ph0ubDRfXoH9LuVbtDJzMJ1r6O4DjFQU8Icd0bBDxUhIZ7+z/Alilz4ETCEsffLl6ZzRXvQdd+7pWhYavuyut52ImfFLhjsWuVYVmE+aybc1sPY6r7DTfbYz8E+aXM=
  distributions: sdist bdist_wheel
  on:
    tags: true
    condition: "$TOXENV = quality"
